### ISSUE TITLE
Extension installed and enabled but doesn't work

### ISSUE THREAD

**Issue by warpdesign** [georapbox/brackets-angular-snippets#1]
I have installed the extension, enabled it in the edit menu, restarted brackets but it still doesn't work. Typing "ngmodule" then tab won't don't anything but insert a tab.

I think I found the problem: it seems the extension checks the scope at which the pointer is placed. And only insert snippets if it's at the root of the file.

So:

(function() {
ngmodule ->
}();

Won't work.

But:

ngmodule ->

Will. It looks like a bug to me.

**Comment by georapbox** [comment]
You are right! It was a bug but it was because of the "tab" character before the inserted snippet. Careless mistake my my side. Update to v.0.1.1 will fix this issue. Thanks for the feedback!

**Comment by warpdesign** [comment]
Great, thanks!
